version: '3.3'

services:
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  frontend:
    image: dagandersen/frontend
    ports:
      - '3000:3000'
    deploy:
      replicas: 2

  custom-api:
    image: dagandersen/backend
    ports:
      - '5002:5001'
    command: bash -c '/wait && npm start'
    environment:
      - PSQL_DB_NAME=$PSQL_DB_NAME
      - PSQL_DB_USER_NAME=$PSQL_DB_USER_NAME
      - PSQL_DB_USER_PASSWORD=$PSQL_DB_USER_PASSWORD
      - PSQL_HOST_NAME=$PSQL_HOST_NAME
      - PSQL_HOST_PORT=$PSQL_HOST_PORT
      - PSQL_SSL_MODE=$PSQL_SSL_MODE
      - WAIT_HOSTS=$WAIT_HOSTS
    deploy:
      replicas: 5
